[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ag"
version = "0.1.2"
description = 'A command-line AI assistant'
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
keywords = []
authors = [
  { name = "srcres258", email = "src.res.211@gmail.com" }
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "openai>=1.16.2",
  "termcolor>=2.4.0",
  "prompt-toolkit>=3.0.43"
]

[project.urls]
Issues = "https://github.com/srcres258/ag/issues"
Source = "https://github.com/srcres258/ag"

[project.scripts]
ag = "main:main"

[tool.hatch.build.targets.sdist]
ignore-vcs = true
include = ["src/main.py"]

[tool.hatch.build.targets.wheel]
packages = ["src/main.py"]
